"""Which land class sits under which, generated rather than curated.

The layering mints one flow object per land class a source flow reaches, and
this pass hangs each of them under the nearest class above it:

    Cropland, non-irrigated, intensive
      -> Cropland, non-irrigated
        -> Cropland

**Every edge is generated by field subsumption**, which is
`plans/land-class-taxonomy.md` §3.7's point and not an implementation detail.
Dropping a land class's most specific stated qualifier gives its parent, so the
whole edge set is this project's by construction and no edge can be published as
ENVO's or GET's that they do not assert.  The material taxonomy had to record a
`broader_source` on all 119 of its edges precisely because its hierarchy was
hand-written and had to be told apart from ENVO's; here there is nothing to tell
apart.

**Nothing is minted.**  The published scheme is the *reached* space -- the 336
classes three source lists between them ship -- and an ancestor no source flow
lands on is not carried.  `(CROPLAND, rainfed, intensive)` therefore hangs off
whichever of `(CROPLAND, rainfed)` and `(CROPLAND)` this build actually has,
which is the rule the material taxonomy already follows for its intermediates
and the rule `flow_layers/non_material.py` follows when it declines to mint a
parent for a family of one.  A class with no reached ancestor is a root and gets
no parent, which is a statement rather than a gap.

`brightway:baseIntervention`, not `brightway:baseSubstance`.  That term means the
undifferentiated *substance* a qualified flow was split from, and it says
substance because it means it (#70).  A land class has no base substance for the
same reason noise has none: it is not matter, which is why the semantic typing
gives it no chemical class at all.

The object id a class mints under is a function of the class, so this pass
recomputes it rather than being handed a map.  Both ends read
`stable_flow_object_id("fo", f"land:{key}")`, so the layering and this pass
cannot disagree about which object is which class -- and a build that carries
only some of the classes (a bounded run, or a list that ships fewer) links only
what it has, rather than pointing at an object that is not there.
"""

from __future__ import annotations

from brightway_flows.domain.flow_object import FlowObject, stable_flow_object_id
from brightway_flows.domain.land_flow_classes import published_land_classes
from brightway_flows.domain.land_use import LandUse

#: How a land class's flow object id is composed.  One spelling, read by the
#: layering that mints the object and by this pass that finds it again.
LAND_OBJECT_BASIS = "land:{key}"


def land_object_id(land_use: LandUse) -> str:
    """The flow object id *land_use* mints under."""
    return stable_flow_object_id("fo", LAND_OBJECT_BASIS.format(key=land_use.key))


def attach_land_hierarchy(
    flow_objects: list[FlowObject],
) -> tuple[list[FlowObject], dict[str, int]]:
    """Link every land object to the nearest land object above it.

    Returns *flow_objects* unchanged in length -- nothing is minted -- and a
    tally.  ``land_classes_rooted`` is the number with no reached ancestor,
    which is the one to watch: it should be the bare `(direction, cover)`
    classes and nothing else, and a run where it jumps is a run where a whole
    branch stopped being reached.
    """
    reached = published_land_classes()
    by_id = {land_object_id(value): value for value in reached.values()}
    present = {obj.flow_object_id for obj in flow_objects}

    linked = 0
    rooted = 0
    for obj in flow_objects:
        land_use = by_id.get(obj.flow_object_id)
        if land_use is None:
            continue
        parent_id = ""
        # `broader_chain` is this value first, then its ancestors nearest-first.
        # Skipping the head is what makes this a parent rather than a self-link.
        for ancestor in land_use.broader_chain()[1:]:
            candidate = land_object_id(ancestor)
            if ancestor.key in reached and candidate in present:
                parent_id = candidate
                break
        if parent_id:
            obj.parent_intervention_id = parent_id
            linked += 1
        else:
            rooted += 1

    return flow_objects, {
        "land_classes_seen": linked + rooted,
        "land_classes_linked": linked,
        "land_classes_rooted": rooted,
    }
