"""The environmental material a flow is made of, and where its name comes from.

The context says where a flow crossed the system boundary and the chemistry says
which molecule it is.  Neither says what the *stuff* was: `sea water`,
`cooling water`, `brine` and `rainwater` are all H2O, all CAS 7732-18-5, and the
only place that difference lived was the source list's free-text flow name.
Because `pipeline/deduplication.py` signs on every semantic field of an
elementary flow, a difference held in no field is a difference that collapses --
which is #31, where a balanced pair of characterisation factors became a
one-sided charge.  See `plans/water-taxonomy.md`.

This module owns the two files that give the material somewhere to live:

- `environmental-materials.json` -- the taxonomy.  Our own SKOS scheme, whose
  concepts carry `skos:broader` to each other and `skos:*Match` out to ENVO and
  AGROVOC.  The hierarchy is **ours**: it states `lake water skos:broader
  surface water`, which the LCA reading needs and ENVO declines to assert, and
  saying it inside our scheme says nothing about what ENVO asserts inside ENVO.
- `material-anchor-snapshot.json` -- what those two authorities actually say
  about every class the taxonomy cites, resolved by
  `tools/resolve_material_anchors.py`.  An accession is eight digits and a typo
  is a different published class that still resolves, so the citations are
  checked against this offline rather than trusted.

Two authorities and not one, with a clean division of labour: **ENVO types the
material** -- what the stuff is -- and **AGROVOC types the accounting category**
-- how a method counts it.  `green water` is the case that needs the second:
it is a water-footprint boundary rather than a kind of stuff, and no OBO
ontology carries it.
"""

from __future__ import annotations

from functools import lru_cache
from typing import Any

import orjson
from brightway_flows.filesystem import PACKAGE_DATA_DIR

DATA_DIR = PACKAGE_DATA_DIR

#: What ENVO and AGROVOC say, pinned.  Package data rather than a live lookup:
#: a suite that reached OLS4 would fail on a train, and one that reached it in
#: CI would make an EBI outage look like a broken commit.
ANCHOR_SNAPSHOT_FILEPATH = DATA_DIR / "material-anchor-snapshot.json"


@lru_cache(maxsize=None)
def anchor_snapshot() -> dict[str, Any]:
    """The resolved anchors, keyed ``{"envo": {...}, "agrovoc": {...}}``.

    :raises FileNotFoundError: if the snapshot is absent.  It is not optional --
        without it no citation is checked -- so its absence is an error rather
        than an empty mapping, which would look like a clean run that verified
        everything.
    """
    if not ANCHOR_SNAPSHOT_FILEPATH.exists():
        raise FileNotFoundError(
            f"Material anchor snapshot not found at {ANCHOR_SNAPSHOT_FILEPATH}. "
            "Run `uv run python tools/resolve_material_anchors.py`."
        )
    return orjson.loads(ANCHOR_SNAPSHOT_FILEPATH.read_bytes())


#: The taxonomy.  Generated by `tools/build_environmental_materials.py`, which
#: computes each edge's provenance against the snapshot rather than taking it on
#: trust; hand-editing it would silently make an edge of ours look like ENVO's.
MATERIALS_FILEPATH = DATA_DIR / "environmental-materials.json"

#: `broader_source` values, in decreasing order of external support.
BROADER_ASSERTED = "asserted"      # the authority states this exact edge
BROADER_SHORTENED = "shortened"    # it states it through a class we do not carry
BROADER_OURS = "ours"              # it does not state it, transitively or at all
BROADER_ROOT = "root"              # no parent within the scheme


@lru_cache(maxsize=None)
def material_concepts() -> dict[str, dict[str, Any]]:
    """The taxonomy, keyed by local id.

    A concept is not always a flow object: `saline_water` exists so sea water and
    brine have the parent ENVO gives them, and nothing maps onto it, so its
    `flow_object_id` is None.  A caller minting objects has to skip those rather
    than treat them as unassigned.
    """
    if not MATERIALS_FILEPATH.exists():
        raise FileNotFoundError(
            f"Material taxonomy not found at {MATERIALS_FILEPATH}. "
            "Run `uv run python tools/build_environmental_materials.py`."
        )
    payload = orjson.loads(MATERIALS_FILEPATH.read_bytes())
    return {concept["id"]: concept for concept in payload["concepts"]}


@lru_cache(maxsize=None)
def concept_by_flow_object() -> dict[str, dict[str, Any]]:
    """``flow_object_id -> concept``, for the objects a concept mints.

    The reverse of what the taxonomy states, so nothing has to be threaded from
    layering to typing: both ends read the same file and cannot disagree about
    which object is which material.
    """
    return {
        concept["flow_object_id"]: concept
        for concept in material_concepts().values()
        if concept.get("flow_object_id")
    }


def broader_chain(concept_id: str) -> list[str]:
    """*concept_id* and its ancestors, nearest first, ending at a root."""
    concepts = material_concepts()
    chain: list[str] = []
    current: str | None = concept_id
    while current:
        if current in chain:  # pragma: no cover -- a cycle is a build-time error
            raise ValueError(f"cycle in the material taxonomy at {current!r}")
        chain.append(current)
        current = concepts[current].get("broader")
    return chain


#: Which concept each source flow is made of.  Curated, because no algorithm
#: reads `Water, salt, sole` and knows it is brine.
FLOW_MATERIALS_FILEPATH = DATA_DIR / "water-flow-materials.json"


class MaterialRuleError(ValueError):
    """A `water-flow-materials.json` row is unusable, or two rows disagree."""


@lru_cache(maxsize=None)
def material_by_source_flow() -> dict[tuple[str, str], dict[str, Any]]:
    """``(source, source_uuid) -> row``.

    Keyed on the pair rather than the uuid alone because the two lists are
    independent vocabularies that happen to share a uuid format, and a source
    naming a flow says nothing about another source's flow of the same name.

    **One flow, one material.**  Two rows for the same pair would be two curated
    statements arbitrated by file order, which is the shape of the defect this
    whole area is being rewritten to remove, so it raises rather than picking.

    :raises MaterialRuleError: on a row missing a field, a row naming a concept
        the taxonomy does not carry, or two rows for one flow.
    """
    if not FLOW_MATERIALS_FILEPATH.exists():
        raise FileNotFoundError(
            f"Flow materials not found at {FLOW_MATERIALS_FILEPATH}. "
            "Run `uv run python tools/build_water_flow_materials.py`."
        )
    concepts = material_concepts()
    rows: dict[tuple[str, str], dict[str, Any]] = {}
    for row in orjson.loads(FLOW_MATERIALS_FILEPATH.read_bytes())["rows"]:
        missing = [
            field
            for field in ("source", "source_uuid", "source_name", "node", "match", "comment")
            if not str(row.get(field) or "").strip()
        ]
        if missing:
            raise MaterialRuleError(
                f"{FLOW_MATERIALS_FILEPATH}: row {row.get('source_uuid')!r} is "
                f"missing {missing}"
            )
        if row["node"] not in concepts:
            raise MaterialRuleError(
                f"{FLOW_MATERIALS_FILEPATH}: row {row['source_uuid']!r} names "
                f"concept {row['node']!r}, which environmental-materials.json "
                "does not carry"
            )
        key = (str(row["source"]).strip(), str(row["source_uuid"]).strip())
        if key in rows and rows[key]["node"] != row["node"]:
            raise MaterialRuleError(
                f"{FLOW_MATERIALS_FILEPATH}: {key} is assigned both "
                f"{rows[key]['node']!r} and {row['node']!r}. One flow, one material."
            )
        rows[key] = row
    return rows


def material_for_source_flow(source: str, source_uuid: str) -> str | None:
    """The concept id *source_uuid* is made of, or None if no row names it.

    None is the answer for almost every flow in the list: this file covers water,
    and a substance with no material axis is not a gap in it.
    """
    row = material_by_source_flow().get(
        (str(source or "").strip(), str(source_uuid or "").strip())
    )
    return row["node"] if row else None


def flow_object_basis_for(concept_id: str) -> str | None:
    """The id basis the concept's flow object is minted from, or None.

    None for a concept nothing maps onto -- `saline_water` -- which a caller
    minting objects has to skip rather than treat as unassigned.
    """
    concept = material_concepts().get(concept_id)
    return concept["flow_object_basis"] if concept else None


#: The body a **withdrawal** of each material was taken from.
#:
#: A rule rather than a table of flows, and it only reads one way.  Water taken
#: from a lake is lake water and was taken from a lake: for a withdrawal the
#: kind of water and the body it came from are the same fact stated twice, which
#: is what `water-taxonomy-overview.md` §2 says in words.  For a *discharge*
#: they are two different facts -- water released into a lake is plain water,
#: and the lake is where it went -- so nothing here is ever applied to an
#: emission.
#:
#: Only the six materials that name a body are here.  `fresh water` and
#: `rainwater` are qualities of the water rather than places it was found;
#: `cooling water` and `turbine water` name what it was used for; `brine` occurs
#: in the ocean and in salt domes alike.  A material absent from this mapping
#: leaves the body exactly as the source list stated it, which for a source that
#: states nothing is `Unknown` -- the honest answer, and the one those rows had
#: before this existed.
WITHDRAWAL_WATER_BODY: dict[str, str] = {
    "lake_water": "Lake",
    "river_water": "River",
    "sea_water": "Ocean",
    "surface_water": "Surface water",
    "groundwater": "Unconfined aquifer",
    "fossil_groundwater": "Confined aquifer with fossil groundwater",
}


def withdrawal_water_body(concept_id: str) -> str | None:
    """The body a withdrawal of *concept_id* was taken from, or None.

    None for most materials, and for every concept that is not water at all.
    A caller must treat None as "leave the body alone" rather than as "Unknown":
    the two look the same on a source that states no body and are not the same
    claim.
    """
    return WITHDRAWAL_WATER_BODY.get(concept_id)


def envo_anchor(accession: str) -> dict[str, Any] | None:
    """One ENVO class as the authority describes it, or None if uncited.

    *accession* is the underscore form, ``ENVO_00002149`` -- the shape an OBO
    IRI ends in, rather than the colon CURIE, so a caller holding an IRI does
    not have to translate before looking it up.
    """
    return anchor_snapshot()["envo"].get(accession)


def agrovoc_anchor(local_id: str) -> dict[str, Any] | None:
    """One AGROVOC concept as the authority describes it, or None if uncited."""
    return anchor_snapshot()["agrovoc"].get(local_id)
