"""Which particle size window a flow was cut at.

The unit says how much, the context says where it went, and neither says
**which particles were counted**.  `Particulates, < 10 um`, `particles (PM10)`
and `Particulate Matter, < 2.5 um` are three source lists' spellings of two
windows, and until this module the only place the window lived was the flow
object's name.

Two things follow from a window held in no field, and #153 is both of them.  A
row reporting PM10 minted a substance of its own beside the PM10 the list
already published, with one elementary flow and no characterisation factors at
all.  And a row reporting the *coarse fraction* -- 2.5 to 10 micrometres --
could reach `Particles (PM10)` by resembling it, which four BAFU rows did, on an
alternative label that a decision taken for ecoinvent had left on that flow.
Neither is a mapping anybody wrote down.

**A window is a pair of aerodynamic-diameter bounds**, and the pair is the
identity::

    BAFU       Particulates, < 10 um     \\
    Stepwise   Particulates, < 10 um      |--> (--, 10 um) --> Particles (PM10)
    EF 3.1     particles (PM10)          /

    ecoinvent  Particulates, > 2.5 um, and < 10um --> (2.5, 10 um) --> a different flow

Two spellings of one window are one thing with no crosswalk row, and two windows
are two things however alike they are spelled.  See
`plans/particulate-taxonomy.md`.

**Aerodynamic diameter, not diameter.**  It is not a length: it is the diameter
of the unit-density sphere that settles at the same speed, so even the selection
criterion is an instrument's answer.

**This vocabulary is ours, and nothing in it cites an authority.**  The water
and land taxonomies anchor out to ENVO, AGROVOC and IUCN GET because those
authorities carry the concepts they need.  For particle size they do not: the
survey in `plans/particulate-taxonomy.md` §2 found two usable classes out of
seven, both defined on plain *diameter* where every list here means aerodynamic
diameter and both restricted to *solid particles* where PM includes droplets,
and nothing anywhere for a band -- not the 0.2-2.5 um slice, not the coarse
fraction, not the above-ten class.  Two loose citations out of seven make a
scheme look anchored when five sevenths of it is not, and invite a reader to
take our bounds for the authority's.  So there are none, and the bounds are what
this is checked by instead.

This module owns the two files that give the window somewhere to live:

- `particulate-size-classes.json` -- the vocabulary.  Seven concepts, each with
  its window, its parent and its reason.  Generated by
  `tools/build_particulate_size_classes.py`, which validates its own output
  through this module's reader before writing it.
- `particulate-flow-classes.json` -- which window each source flow was cut at,
  one row per `(source, uuid)`.  **Curated, never parsed.**  BAFU ships both
  `Particulates` and `Particulates, unspecified` and Stepwise 2006 characterises
  them differently, so whether those two names mean one thing is a judgement
  about what a vendor meant rather than a string comparison.  A rule that
  answered it in the build would answer it silently, and would answer it the
  same way for the next list without being asked.

**What kind of thing these are is a different question, answered elsewhere.**
All seven classes are `brightway:AggregateMeasurement` -- a quantity fixed by
the procedure that produces it, not a substance -- which
`aggregate-measurements.json` states once for the family.  This module says
*which cut*; that file says *not a substance*.  Neither is a substitute for the
other, and nothing here types a flow.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from typing import Any

import orjson

from brightway_flows.filesystem import PACKAGE_DATA_DIR

DATA_DIR = PACKAGE_DATA_DIR

#: The on-disk format of the files below, and of nothing else.  Not the
#: version of the list this project publishes, which is
#: `domain.schema.SCHEMA_VERSION`.
DECISIONS_SCHEMA_VERSION = 1

#: The vocabulary.  Generated, not hand-edited: the tool validates the scheme
#: through this module's reader before writing it, and a hand edit is how a
#: window that contradicts its parent gets past review.
SIZE_CLASSES_FILEPATH = DATA_DIR / "particulate-size-classes.json"


class ParticulateSizeError(ValueError):
    """A size-class file that cannot be read as one.

    Raised rather than skipped, for the reason every curated file in this
    project raises: a row that is silently ignored is a decision that looks
    applied and is not.
    """


@dataclass(frozen=True)
class SizeClass:
    """One particle size window.

    *lower_um* and *upper_um* are aerodynamic-diameter bounds in micrometres,
    ``None`` meaning open on that side.  ``None`` on **both** means the source
    stated no cut at all, which is the absence of a statement rather than a
    window of infinite width -- see :meth:`window`.
    """

    id: str
    label: str
    definition: str
    broader: str | None
    selection: str
    lower_um: float | None
    upper_um: float | None
    flow_object_basis: str
    flow_object_id: str
    comment: str
    #: The `Particulates` spellings this window is always published under as
    #: alternative labels, beside its `Particles (...)` preferred label.  The
    #: ecoinvent-2 form three SimaPro-shaped lists inherit, stated by the
    #: scheme so that a reader's search finds the window whichever vendor's
    #: rows happened to reach it.  See `plans/particle-family.md` §2.
    alt_labels: tuple[str, ...] = ()
    #: The text the bound is read from -- a Directive, a standard, or `by
    #: construction from the bounds` -- so a reader can check what
    #: `upper_um` means without taking the number on trust.  Not an
    #: ontology class: none carries these (plans/particle-family.md section 1).
    definition_source: str = ""

    @property
    def states_a_cut(self) -> bool:
        """Did the source say where the sample was cut?

        False for exactly one class, and the distinction is load-bearing: a row
        that did not state a cut has not stated that the cut was everywhere, so
        `unsized` is not a superset of PM10 and nothing may treat it as one.
        """
        return not (self.lower_um is None and self.upper_um is None)

    def window(self) -> tuple[float, float] | None:
        """The window as a closed pair, or ``None`` where no cut was stated.

        An open lower bound reads as zero and an open upper bound as infinity,
        which is what comparing two windows needs.  ``None`` is returned rather
        than ``(0, inf)`` so that a caller has to decide what to do about a row
        that said nothing, instead of being handed an answer that looks like a
        measurement.
        """
        if not self.states_a_cut:
            return None
        return (
            0.0 if self.lower_um is None else float(self.lower_um),
            float("inf") if self.upper_um is None else float(self.upper_um),
        )


@lru_cache(maxsize=None)
def _payload() -> dict[str, Any]:
    if not SIZE_CLASSES_FILEPATH.exists():
        raise FileNotFoundError(
            f"Particulate size classes not found at {SIZE_CLASSES_FILEPATH}. "
            "Run `uv run python tools/build_particulate_size_classes.py`."
        )
    payload = orjson.loads(SIZE_CLASSES_FILEPATH.read_bytes())
    version = payload.get("schema_version")
    if version != DECISIONS_SCHEMA_VERSION:
        raise ParticulateSizeError(
            f"{SIZE_CLASSES_FILEPATH}: schema_version is {version!r}, and this "
            f"reader is written for {DECISIONS_SCHEMA_VERSION}"
        )
    return payload


def check_nesting(classes: dict[str, SizeClass]) -> None:
    """Every declared parent is the smallest class that properly contains it.

    The scheme is seven hand-written concepts, which is small enough to get
    subtly wrong and too small for anything else to catch it.  The bounds are
    evidence a reviewer can check where a label is not, so they are what decides
    here.  Three failures, and each is a mistake somebody reading labels would
    make:

    * **two classes stating one window** -- a second PM10 under another name;
    * **a parent that does not contain the child** -- the 2.5-10 um band pointed
      at PM2.5 because both mention 2.5;
    * **a parent that contains it but is not the nearest one that does** --
      PM0.2 hung off PM10, skipping PM2.5.

    `unsized` states no window, so it is neither checked as a container nor
    checked for one.  What *is* checked is the rule that puts a class under it:
    a class whose parent is the size-unstated root must have no container among
    the sized classes, which is what keeps `Particles (> PM10)` at the top of
    the scheme rather than inside PM10.

    :raises ParticulateSizeError: on any of the three, naming both classes.
    """
    sized = [value for value in classes.values() if value.states_a_cut]

    seen: dict[tuple[float, float], str] = {}
    for value in sized:
        pair = value.window()
        assert pair is not None
        if pair in seen:
            raise ParticulateSizeError(
                f"{SIZE_CLASSES_FILEPATH}: {value.id!r} and {seen[pair]!r} both "
                f"state the window {pair}. Two names for one window is the "
                "collapse this scheme exists to stop."
            )
        seen[pair] = value.id

    def contains(outer: SizeClass, inner: SizeClass) -> bool:
        wide, narrow = outer.window(), inner.window()
        assert wide is not None and narrow is not None
        return wide[0] <= narrow[0] and narrow[1] <= wide[1]

    def width(value: SizeClass) -> float:
        pair = value.window()
        assert pair is not None
        return pair[1] - pair[0]

    for value in sized:
        containers = [
            other
            for other in sized
            if other.id != value.id and contains(other, value)
        ]
        if not containers:
            parent = classes.get(value.broader or "")
            if parent is None or parent.states_a_cut:
                raise ParticulateSizeError(
                    f"{SIZE_CLASSES_FILEPATH}: {value.id!r} is inside no other "
                    f"class, so its parent must be the size-unstated root; it "
                    f"declares {value.broader!r}."
                )
            continue
        nearest = min(containers, key=width)
        if value.broader != nearest.id:
            raise ParticulateSizeError(
                f"{SIZE_CLASSES_FILEPATH}: {value.id!r} declares {value.broader!r} "
                f"as its parent, but the smallest class containing "
                f"{value.window()} is {nearest.id!r} {nearest.window()}."
            )


def classes_from_payload(payload: dict[str, Any]) -> dict[str, SizeClass]:
    """Parse and validate one scheme payload into records.

    Public and taking the payload rather than reading the file, so that
    `tools/build_particulate_size_classes.py` can check what it is about to
    write with the same code that will read it back.  A generator whose output
    its own reader rejects is the failure worth making impossible.

    :raises ParticulateSizeError: on a concept naming a parent the scheme does
        not carry, two concepts claiming one id, or a nesting the bounds
        contradict.  All three are authoring errors that would otherwise show up
        as a flow landing somewhere surprising three stages later.
    """
    classes: dict[str, SizeClass] = {}
    for concept in payload["concepts"]:
        identifier = str(concept["id"])
        if identifier in classes:
            raise ParticulateSizeError(
                f"{SIZE_CLASSES_FILEPATH}: {identifier!r} is declared twice."
            )
        classes[identifier] = SizeClass(
            id=identifier,
            label=str(concept["label"]),
            definition=str(concept.get("definition") or ""),
            broader=concept.get("broader") or None,
            selection=str(concept["selection"]),
            lower_um=concept.get("lower_um"),
            upper_um=concept.get("upper_um"),
            flow_object_basis=str(concept["flow_object_basis"]),
            flow_object_id=str(concept["flow_object_id"]),
            comment=str(concept.get("comment") or ""),
            alt_labels=tuple(
                str(label).strip()
                for label in concept.get("alt_labels") or ()
                if str(label).strip()
            ),
            definition_source=str(concept.get("definition_source") or "").strip(),
        )

    for identifier, value in classes.items():
        if value.broader and value.broader not in classes:
            raise ParticulateSizeError(
                f"{SIZE_CLASSES_FILEPATH}: {identifier!r} is broader than "
                f"{value.broader!r}, which the scheme does not carry."
            )
    check_nesting(classes)
    check_labels(classes)
    return classes


def _folded(label: str) -> str:
    return " ".join(label.strip().lower().split())


def check_labels(classes: dict[str, SizeClass]) -> None:
    """Every window states at least one `Particulates` spelling, and no name
    is published for two windows.

    The alternative labels are a promise -- a reader searching the export for
    the ecoinvent-2 spelling finds the window -- and a promise kept for six
    windows out of seven is the kind of gap nobody notices.  A name shared by
    two windows would make a search answer twice, which is the collapse the
    scheme exists to stop.

    :raises ParticulateSizeError: on a window with no alternative label, or a
        name (preferred or alternative) two windows both state.
    """
    owners: dict[str, str] = {}
    for value in classes.values():
        if not value.definition_source:
            raise ParticulateSizeError(
                f"{SIZE_CLASSES_FILEPATH}: {value.id!r} states no definition "
                "source, so nothing says what its bound means."
            )
        if not value.alt_labels:
            raise ParticulateSizeError(
                f"{SIZE_CLASSES_FILEPATH}: {value.id!r} states no `Particulates` "
                "spelling to publish as an alternative label."
            )
        for label in (value.label, *value.alt_labels):
            key = _folded(label)
            if key in owners and owners[key] != value.id:
                raise ParticulateSizeError(
                    f"{SIZE_CLASSES_FILEPATH}: {label!r} is a name of both "
                    f"{owners[key]!r} and {value.id!r}."
                )
            owners[key] = value.id


#: How a source row says it is an airborne-particle measurement, and the whole
#: of the test the merge refuses an unread row by.  A prefix rather than a
#: word search, and the same prefixes `tools/build_particulate_flow_classes.py`
#: selects rows by, so that what the tool would have shown a curator and what
#: the merge refuses are one population.  Composition names -- `Soot`, `Zinc,
#: fume or dust`, `Silicate particles` -- do not begin with the word and are
#: not particles-by-size; the chemistry rules place them.
_PARTICLE_NAME_PREFIXES = ("particle", "particulate")


def names_a_particle_by_size(name: str) -> bool:
    """Whether *name* is written the way a size-cut particle row is written."""
    return _folded(name).startswith(_PARTICLE_NAME_PREFIXES)


class UnreadParticleRowError(ParticulateSizeError):
    """A particle row no curated row has read, met by a build.

    The land taxonomy refuses a row in a compartment told apart by name that
    matches no rule, and the merge stops (#52).  This is the same refusal for
    particles: a row named `Particulates, ...` that `particulate-flow-classes.json`
    has no row for used to fall through to the label branch and mint a
    substance with no window and no factor, silently -- `Particulates, SPM`
    on the build of 2 September 2026.  Now it names the list, the row and the
    file a curator writes the reading in, and the merge does not finish.
    """

    def __init__(self, *, source: str, source_uuid: str, name: str, context: Any):
        self.source = source
        self.source_uuid = source_uuid
        self.name = name
        self.context = context
        super().__init__(
            f"{source}: {name!r} ({source_uuid}, {list(context or [])}) is an "
            "airborne-particle row that particulate-flow-classes.json has not "
            "read. Add its reading to READINGS in "
            "tools/build_particulate_flow_classes.py and regenerate the file; "
            "the merge does not guess a size window."
        )


@lru_cache(maxsize=None)
def size_classes() -> dict[str, SizeClass]:
    """The taxonomy, keyed by local id, in file order.

    Cached and taking nothing, because its path is fixed.
    """
    return classes_from_payload(_payload())


def size_class(class_id: str) -> SizeClass | None:
    """The window *class_id* names, or ``None``."""
    return size_classes().get(str(class_id or "").strip())


@lru_cache(maxsize=None)
def class_by_flow_object() -> dict[str, SizeClass]:
    """``flow_object_id -> class``, the reverse of what the taxonomy states.

    So that nothing has to be threaded from layering to publication: both ends
    read the same file and cannot disagree about which object is which window.
    """
    return {size.flow_object_id: size for size in size_classes().values()}


def flow_object_basis_for(class_id: str) -> str | None:
    """The id basis *class_id*'s flow object is minted from, or ``None``.

    Every class in this scheme mints an object -- unlike the material taxonomy,
    where `saline_water` exists only to give sea water and brine the parent ENVO
    gives them -- so ``None`` here means the id is not one of ours.
    """
    found = size_class(class_id)
    return found.flow_object_basis if found else None


def broader_chain(class_id: str) -> list[str]:
    """*class_id* and its ancestors, nearest first, ending at the root."""
    classes = size_classes()
    chain: list[str] = []
    current: str | None = str(class_id or "").strip()
    while current:
        if current in chain:  # pragma: no cover -- a cycle is a build-time error
            raise ParticulateSizeError(
                f"cycle in the particulate taxonomy at {current!r}"
            )
        if current not in classes:
            raise ParticulateSizeError(
                f"{SIZE_CLASSES_FILEPATH}: {current!r} is not a size class."
            )
        chain.append(current)
        current = classes[current].broader
    return chain


# ── which window each source flow was cut at ─────────────────────────────────

#: The curated assignment.  Generated by
#: `tools/build_particulate_flow_classes.py` from the shipped vendor files, with
#: `size_class` and `source_category` as the only curated columns -- so a
#: reviewer checking a row is checking two fields against four they can trust.
FLOW_CLASSES_FILEPATH = DATA_DIR / "particulate-flow-classes.json"

#: The values `source_category` may take, and the whole of the second axis.
#:
#: Closed, because an open field is where `(stationary)`, `Stationary` and
#: `stationary source` become three answers to one question.  Empty means the
#: source said nothing about what emitted the particles, which is most rows.
#: `process` is AGRIBALYSE's third answer -- particles from a process rather
#: than from combustion at a stationary or a mobile source (#190).
SOURCE_CATEGORIES = frozenset({"", "stationary", "mobile", "process"})

#: The fields every row must carry a value for.  `source_category` is absent:
#: most rows state none, and requiring it would make "the vendor did not say"
#: indistinguishable from a missing column.
_REQUIRED_FIELDS = ("source", "source_uuid", "source_name", "size_class", "comment")


@dataclass(frozen=True)
class ParticulateFlowClass:
    """One source flow's size window, and what the vendor shipped it as.

    *size_class* and *source_category* are the curated part.  Everything else is
    the vendor's, taken mechanically from the shipped file, so a reviewer
    checking a row is checking two fields against four they can trust.

    *source_category* says what emitted the particles -- `stationary`, `mobile`
    -- and is **not** a size.  It is empty for all but the rows whose names
    state one.  It does not change which flow object the row reaches: Stepwise
    2006, the only list in scope that characterises those rows, gives plain,
    mobile and stationary PM10 the same factor, so a separate identity would buy
    a distinction no method uses at the cost of every factor the row could have
    had.  See `plans/particulate-taxonomy.md` §3.3.
    """

    source: str
    source_uuid: str
    source_name: str
    size_class: SizeClass
    comment: str
    source_category: str = ""
    source_context: tuple[str, ...] = ()
    unit: str = ""


@lru_cache(maxsize=None)
def particulate_class_by_source_flow() -> dict[tuple[str, str], ParticulateFlowClass]:
    """``(source, source_uuid) -> row``, validated.

    Keyed on the pair rather than the uuid alone, for the reason
    `material_by_source_flow` gives: the lists are independent vocabularies that
    happen to share a uuid format, and one list naming a flow says nothing about
    another's flow of the same name.

    **One flow, one window.**  Two rows for one pair would be two curated
    statements arbitrated by file order, which is the collapse the whole
    taxonomy exists to undo, so it raises rather than picking.

    :raises ParticulateSizeError: on a row missing a field, a row naming a class
        the scheme does not carry, a source category outside
        :data:`SOURCE_CATEGORIES`, or two rows for one flow.
    """
    if not FLOW_CLASSES_FILEPATH.exists():
        raise FileNotFoundError(
            f"Particulate flow classes not found at {FLOW_CLASSES_FILEPATH}. "
            "Run `uv run python tools/build_particulate_flow_classes.py`."
        )
    payload = orjson.loads(FLOW_CLASSES_FILEPATH.read_bytes())
    version = payload.get("schema_version")
    if version != DECISIONS_SCHEMA_VERSION:
        raise ParticulateSizeError(
            f"{FLOW_CLASSES_FILEPATH}: schema_version is {version!r}, and this "
            f"reader is written for {DECISIONS_SCHEMA_VERSION}"
        )

    classes = size_classes()
    rows: dict[tuple[str, str], ParticulateFlowClass] = {}
    for row in payload.get("rows") or ():
        missing = [
            field
            for field in _REQUIRED_FIELDS
            if not str(row.get(field) or "").strip()
        ]
        if missing:
            raise ParticulateSizeError(
                f"{FLOW_CLASSES_FILEPATH}: row {row.get('source_uuid')!r} is "
                f"missing {missing}"
            )
        class_id = str(row["size_class"]).strip()
        if class_id not in classes:
            raise ParticulateSizeError(
                f"{FLOW_CLASSES_FILEPATH}: row {row['source_uuid']!r} names size "
                f"class {class_id!r}, which particulate-size-classes.json does "
                "not carry."
            )
        category = str(row.get("source_category") or "").strip()
        if category not in SOURCE_CATEGORIES:
            raise ParticulateSizeError(
                f"{FLOW_CLASSES_FILEPATH}: row {row['source_uuid']!r} states the "
                f"source category {category!r}, which is not one of "
                f"{sorted(SOURCE_CATEGORIES)}."
            )

        key = (str(row["source"]).strip(), str(row["source_uuid"]).strip())
        existing = rows.get(key)
        if existing is not None and existing.size_class.id != class_id:
            raise ParticulateSizeError(
                f"{FLOW_CLASSES_FILEPATH}: {key} is assigned both "
                f"{existing.size_class.id!r} and {class_id!r}. One flow, one "
                "window."
            )
        rows[key] = ParticulateFlowClass(
            source=key[0],
            source_uuid=key[1],
            source_name=str(row["source_name"]),
            size_class=classes[class_id],
            comment=str(row["comment"]),
            source_category=category,
            source_context=tuple(
                str(part) for part in row.get("source_context") or ()
            ),
            unit=str(row.get("unit") or ""),
        )
    return rows


def size_class_for_source_flow(source: str, source_uuid: str) -> SizeClass | None:
    """The window *source_uuid* was cut at, or ``None`` if no row names it.

    ``None`` is the answer for almost every flow in the list: this file covers
    airborne particles, and a substance with no size window is not a gap in it.
    """
    row = particulate_class_by_source_flow().get(
        (str(source or "").strip(), str(source_uuid or "").strip())
    )
    return row.size_class if row else None


def source_category_for_source_flow(source: str, source_uuid: str) -> str:
    """What emitted the particles, or ``""`` where the source did not say.

    Separate from :func:`size_class_for_source_flow` because it answers a
    different question and must not be mistaken for part of the identity: two
    rows differing only in this reach the same flow object.
    """
    row = particulate_class_by_source_flow().get(
        (str(source or "").strip(), str(source_uuid or "").strip())
    )
    return row.source_category if row else ""


@lru_cache(maxsize=1)
def reached_size_classes() -> dict[str, SizeClass]:
    """Every window a source flow actually reaches, keyed by id.

    The *reached* space, not the declared one.  A class nothing reaches would be
    a concept minting a flow object no row lands on, which is worth being able
    to see.
    """
    return {
        row.size_class.id: row.size_class
        for row in particulate_class_by_source_flow().values()
    }
