#!/usr/bin/env python
"""Shortlist the applied CC/ChEBI renames that may have narrowed a flow's scope.

`cc_chebi_agreement` is in `DEFAULT_APPROVED_RULES`, so its renames publish
without a curator seeing them (#221).  The evidence for that default is an audit
of identity -- is the replacement a name the cited CAS actually has, per Common
Chemistry and ChEBI? -- which came back with 0 unsupported identities in 724
pairs, against 80 of 114 for the PubChem-backed rule that #222 then removed.

**That audit cannot see specificity** (#224).  `'Xylene (all isomers)' ->
'Xylene'` passes it, because `xylene` is a name CAS 1330-20-7 holds and `xylene
(all isomers)` is not -- so the archetypal scope loss, the case that motivated
the curation gate in #220, scores in the benign bucket of the method that now
justifies applying such renames unreviewed.

This tool reads the renames that were applied back out of the change log, audits
each for identity the way `tools/build_label_worklist.py` audits the queued ones,
and then asks the second question the audit cannot: **does the replacement drop
a qualifier the current name carries?**  A scope qualifier, a carbon range, a
locant, a stereo prefix, a salt or hydrate word, a bracketed or comma-separated
clause.

The answer shortlists; it does not decide.  A pattern over chemical names
misfires -- #220 abandoned exactly this heuristic after three iterations -- so
what comes out is a list a chemist works through, ordered so the likeliest rows
come first.  **Every applied pair is in the output**, shortlisted or not, because
a shortlist that silently dropped the rest would read as coverage.

Rows are shaped like `preferred-label-decisions.json` entries, as the worklist's
are: rule on one by setting `decision`, writing `notes`, dropping the `audit`
block and moving the row across.  A `reject` beats `DEFAULT_APPROVED_RULES`, so
a ruling here is what stops a narrowing rename in the next run.

    tools/build_scope_narrowing_shortlist.py [--database PATH] [--output PATH]

Defaults read `consensus-flows.sqlite3` from the platform data directory and
write `docs/reference/scope-narrowing-shortlist.json`.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

from brightway_flows.curation.applied_renames import applied_cc_chebi_renames
from brightway_flows.curation.label_audit import (
    SUPPORTED_VERDICTS,
    SourceNames,
    public_evidence,
    verdict_over_cas,
)
from brightway_flows.curation.qualifier_loss import assess
from brightway_flows.filesystem import CONSENSUS_DB_FILEPATH
from brightway_flows.pipeline.review_tables import read_pipeline_run

DEFAULT_OUTPUT = (
    Path(__file__).resolve().parent.parent
    / "docs" / "reference" / "scope-narrowing-shortlist.json"
)

COMMENT = (
    "Applied cc_chebi_agreement renames, generated by "
    "tools/build_scope_narrowing_shortlist.py from the consensus database. These "
    "renames were published without a ruling, because the rule is in "
    "DEFAULT_APPROVED_RULES. `audit.verdict` is the identity question -- is each "
    "name a name the cited CAS actually has, per Common Chemistry and ChEBI -- and "
    "it cannot see a replacement that names something broader than the flow is. "
    "`audit.qualifier_loss` is that second question: which qualifiers the current "
    "name carries that the replacement drops. It shortlists for a reader and "
    "decides nothing -- a dropped qualifier is often correct. A row is "
    "`audit.shortlisted` when it drops a scope, salt or hydrate word, or when it "
    "drops anything at all and `audit.reduction` says the replacement is the "
    "current name with something taken out of it rather than a different name; a "
    "systematic name giving way to a common one drops every locant it had, and "
    "that is the improvement the rule exists to make. Shortlisted rows are the "
    "ones to read first; the rest are here so that the population is visible "
    "rather than filtered. Rule on a row by setting "
    "`decision`, writing `notes`, dropping the `audit` block and moving it into "
    "preferred-label-decisions.json, where a `reject` overrides the rule default."
)


def build(db_path: Path) -> dict[str, Any]:
    """The shortlist over every rename `cc_chebi_agreement` applied this run."""
    pairs = applied_cc_chebi_renames(db_path)
    run = read_pipeline_run(db_path)
    sources = SourceNames()

    rows: list[dict[str, Any]] = []
    verdicts: Counter[str] = Counter()
    detectors: Counter[str] = Counter()
    by_verdict: defaultdict[str, Counter[str]] = defaultdict(Counter)
    for pair in pairs:
        evidence = [sources.evidence(cas) for cas in pair.cas_numbers]
        verdict = verdict_over_cas(pair.current, pair.replacement, evidence)
        assessment = assess(pair.current, pair.replacement)

        verdicts[verdict] += 1
        by_verdict[verdict]["pairs"] += 1
        by_verdict[verdict]["flows"] += pair.flow_count
        if assessment.shortlisted:
            by_verdict[verdict]["shortlisted_pairs"] += 1
            by_verdict[verdict]["shortlisted_flows"] += pair.flow_count
            for loss in assessment.losses:
                detectors[loss.detector] += 1

        rows.append({
            "current": pair.current,
            "replacement": pair.replacement,
            "decision": "undecided",
            "notes": "",
            "audit": {
                "shortlisted": assessment.shortlisted,
                "reduction": assessment.reduction,
                "qualifier_loss": [
                    {"detector": loss.detector, "tokens": list(loss.tokens)}
                    for loss in assessment.losses
                ],
                "verdict": verdict,
                "supported": verdict in SUPPORTED_VERDICTS,
                "rule": "cc_chebi_agreement",
                "cas_numbers": pair.cas_numbers,
                "flow_count": pair.flow_count,
                "example_uuid": pair.example_uuid,
                "sources": [public_evidence(item) for item in evidence],
            },
        })

    # Shortlisted first, and within that the pairs that lose the most, because a
    # name dropping a scope word *and* a locant is a likelier narrowing than one
    # dropping a bracket -- and a reader working top-down should meet those
    # first.
    rows.sort(key=lambda row: (
        not row["audit"]["shortlisted"],
        -len(row["audit"]["qualifier_loss"]),
        -row["audit"]["flow_count"],
        row["current"],
    ))
    shortlisted = [row for row in rows if row["audit"]["shortlisted"]]

    return {
        "schema_version": 1,
        "comment": COMMENT,
        "source_run": {
            "database": str(db_path),
            "run_id": run.run_id if run is not None else "",
            "timestamp": run.timestamp if run is not None else "",
        },
        "summary": {
            "pairs": len(rows),
            "flows": sum(row["audit"]["flow_count"] for row in rows),
            "shortlisted_pairs": len(shortlisted),
            "shortlisted_flows": sum(row["audit"]["flow_count"] for row in shortlisted),
            "verdicts": dict(verdicts.most_common()),
            "detectors": dict(detectors.most_common()),
            "by_verdict": {
                verdict: dict(counts) for verdict, counts in sorted(by_verdict.items())
            },
        },
        "decisions": rows,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--database", type=Path, default=CONSENSUS_DB_FILEPATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)

    if not args.database.exists():
        parser.error(
            f"consensus database not found: {args.database}\n"
            "Run `brightway-flows build` first."
        )

    payload = build(args.database)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, ensure_ascii=False)
        handle.write("\n")

    summary = payload["summary"]
    print(f"wrote {args.output}")
    print(f"  {summary['pairs']} applied pairs / {summary['flows']} flows")
    print(
        f"  {summary['shortlisted_pairs']} shortlisted / "
        f"{summary['shortlisted_flows']} flows"
    )
    for verdict, counts in summary["by_verdict"].items():
        print(
            f"    {counts['pairs']:>4} pairs  {verdict}"
            f"  ({counts.get('shortlisted_pairs', 0)} shortlisted)"
        )
    for detector, count in summary["detectors"].items():
        print(f"    {count:>4} shortlisted pairs lose a {detector}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
